[package]
name = "hil-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
unix-utils = { path = "../unix-utils" }
